str = "hi this is Python"
str1 = ("Hi","this","is","Python")
print(len(str))     #len()
print(str.find('s'))    #find()
print(str.index('s'))    #index()
print(str.split())      #split()
print('#'.join(str1))   #join()
print(str.count('i'))   #count()
print(str.upper())      #upper()
print(str.lower())        #lower()
print(str.capitalize())     #capatalize()
print(str.title())        #title()
print(str.swapcase())       #swapcase()
print(str.isalpha())        #isalpha()
print(str.isdigit())        #isdigit()
print(str.isspace())        #isspace()
print(str.isalnum())        #isalnum()
